# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import crowdemotion_api_client_python
from crowdemotion_api_client_python.rest import ApiException
from crowdemotion_api_client_python.apis.research_api import ResearchApi


class TestResearchApi(unittest.TestCase):
    """ ResearchApi unit test stubs """

    def setUp(self):
        self.api = crowdemotion_api_client_python.apis.research_api.ResearchApi()

    def tearDown(self):
        pass

    def test_research_get(self):
        """
        Test case for research_get

        Find all Research
        """
        pass

    def test_research_post(self):
        """
        Test case for research_post

        Create a Research Project
        """
        pass

    def test_research_research_id_delete(self):
        """
        Test case for research_research_id_delete

        Delete Research Project
        """
        pass

    def test_research_research_id_get(self):
        """
        Test case for research_research_id_get

        Find a Research Project
        """
        pass

    def test_research_research_id_put(self):
        """
        Test case for research_research_id_put

        Edit Research Project details
        """
        pass


if __name__ == '__main__':
    unittest.main()
