# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from .content_details import ContentDetails
from .data import Data
from .face_video import FaceVideo
from .face_video_upload import FaceVideoUpload
from .login import Login
from .login_response import LoginResponse
from .media import Media
from .media_creation import MediaCreation
from .metric import Metric
from .metric_creation import MetricCreation
from .research import Research
from .research_creation import ResearchCreation
from .respondent import Respondent
from .respondent_metadata import RespondentMetadata
from .respondent_metadata_response import RespondentMetadataResponse
from .response import Response
from .response_creation import ResponseCreation
from .response_metadata import ResponseMetadata
from .response_metadata_response import ResponseMetadataResponse
from .statistics import Statistics
from .stats import Stats
from .status import Status
from .tags import Tags
from .timeseries import Timeseries
from .user import User
from .user_metadata import UserMetadata
from .user_metadata_response import UserMetadataResponse
from .user_update_body import UserUpdateBody
from .videodetails import Videodetails
