# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class RespondentMetadataResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, respondent_id=None, data=None):
        """
        RespondentMetadataResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'respondent_id': 'str',
            'data': 'Data'
        }

        self.attribute_map = {
            'respondent_id': 'respondentId',
            'data': 'data'
        }

        self._respondent_id = respondent_id
        self._data = data

    @property
    def respondent_id(self):
        """
        Gets the respondent_id of this RespondentMetadataResponse.
        

        :return: The respondent_id of this RespondentMetadataResponse.
        :rtype: str
        """
        return self._respondent_id

    @respondent_id.setter
    def respondent_id(self, respondent_id):
        """
        Sets the respondent_id of this RespondentMetadataResponse.
        

        :param respondent_id: The respondent_id of this RespondentMetadataResponse.
        :type: str
        """

        self._respondent_id = respondent_id

    @property
    def data(self):
        """
        Gets the data of this RespondentMetadataResponse.


        :return: The data of this RespondentMetadataResponse.
        :rtype: Data
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this RespondentMetadataResponse.


        :param data: The data of this RespondentMetadataResponse.
        :type: Data
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
