# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class MediaApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def media_get(self, **kwargs):
        """
        Find all registered Media
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int skip: The number of results to skip.
        :param int limit: The maximum number of results to return.
        :param str where: JSON formatted string condition.
        :param str sort: Attribute used to sort results.
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.media_get_with_http_info(**kwargs)
        else:
            (data) = self.media_get_with_http_info(**kwargs)
            return data

    def media_get_with_http_info(self, **kwargs):
        """
        Find all registered Media
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int skip: The number of results to skip.
        :param int limit: The maximum number of results to return.
        :param str where: JSON formatted string condition.
        :param str sort: Attribute used to sort results.
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['skip', 'limit', 'where', 'sort']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method media_get" % key
                )
            params[key] = val
        del params['kwargs']

        resource_path = '/media'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'skip' in params:
            query_params['skip'] = params['skip']
        if 'limit' in params:
            query_params['limit'] = params['limit']
        if 'where' in params:
            query_params['where'] = params['where']
        if 'sort' in params:
            query_params['sort'] = params['sort']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Media',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def media_media_id_delete(self, media_id, **kwargs):
        """
        Delete Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_delete(media_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.media_media_id_delete_with_http_info(media_id, **kwargs)
        else:
            (data) = self.media_media_id_delete_with_http_info(media_id, **kwargs)
            return data

    def media_media_id_delete_with_http_info(self, media_id, **kwargs):
        """
        Delete Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_delete_with_http_info(media_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['media_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method media_media_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'media_id' is set
        if ('media_id' not in params) or (params['media_id'] is None):
            raise ValueError("Missing the required parameter `media_id` when calling `media_media_id_delete`")

        resource_path = '/media/{media_id}'.replace('{format}', 'json')
        path_params = {}
        if 'media_id' in params:
            path_params['media_id'] = params['media_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'DELETE',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='str',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def media_media_id_get(self, media_id, **kwargs):
        """
        Find a Media
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_get(media_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id: ID of Media to search. (required)
        :param bool presigned_url: Returns the presignedUrl whose value is a signed (protected) URL to hosted video on our premises.
        :return: list[Media]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.media_media_id_get_with_http_info(media_id, **kwargs)
        else:
            (data) = self.media_media_id_get_with_http_info(media_id, **kwargs)
            return data

    def media_media_id_get_with_http_info(self, media_id, **kwargs):
        """
        Find a Media
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_get_with_http_info(media_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id: ID of Media to search. (required)
        :param bool presigned_url: Returns the presignedUrl whose value is a signed (protected) URL to hosted video on our premises.
        :return: list[Media]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['media_id', 'presigned_url']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method media_media_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'media_id' is set
        if ('media_id' not in params) or (params['media_id'] is None):
            raise ValueError("Missing the required parameter `media_id` when calling `media_media_id_get`")

        resource_path = '/media/{media_id}'.replace('{format}', 'json')
        path_params = {}
        if 'media_id' in params:
            path_params['media_id'] = params['media_id']

        query_params = {}
        if 'presigned_url' in params:
            query_params['presignedUrl'] = params['presigned_url']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[Media]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def media_media_id_put(self, media_id, body, **kwargs):
        """
        Update a Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_put(media_id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id:  (required)
        :param MediaCreation body: Request body (required)
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.media_media_id_put_with_http_info(media_id, body, **kwargs)
        else:
            (data) = self.media_media_id_put_with_http_info(media_id, body, **kwargs)
            return data

    def media_media_id_put_with_http_info(self, media_id, body, **kwargs):
        """
        Update a Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_media_id_put_with_http_info(media_id, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int media_id:  (required)
        :param MediaCreation body: Request body (required)
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['media_id', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method media_media_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'media_id' is set
        if ('media_id' not in params) or (params['media_id'] is None):
            raise ValueError("Missing the required parameter `media_id` when calling `media_media_id_put`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `media_media_id_put`")

        resource_path = '/media/{media_id}'.replace('{format}', 'json')
        path_params = {}
        if 'media_id' in params:
            path_params['media_id'] = params['media_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'PUT',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Media',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def media_post(self, body, **kwargs):
        """
        Create new Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_post(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param MediaCreation body: Request body (required)
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.media_post_with_http_info(body, **kwargs)
        else:
            (data) = self.media_post_with_http_info(body, **kwargs)
            return data

    def media_post_with_http_info(self, body, **kwargs):
        """
        Create new Media
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.media_post_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param MediaCreation body: Request body (required)
        :return: Media
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method media_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `media_post`")

        resource_path = '/media'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Media',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))
