# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class MetricApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def metric_get(self, **kwargs):
        """
        List all registered metrics
        <p>Metrics are linked to time-series and define their meaning.</p> <p>Common metric ID are listed below:</p> <table>   <tr><td>id</td><td>Value</td></tr>   <tr><td>1</td><td>Timestamp</td></tr>   <tr><td>2</td><td>Neutral</td></tr>   <tr><td>3</td><td>Happiness</td></tr>   <tr><td>4</td><td>Surprise</td></tr>   <tr><td>5</td><td>Puzzlement</td></tr>   <tr><td>6</td><td>Disgust</td></tr>   <tr><td>7</td><td>Fear</td></tr>   <tr><td>8</td><td>Sadness</td></tr> </table> <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int skip: The number of results to skip.
        :param int limit: The maximum number of results to return.
        :param str where: JSON formatted string condition.
        :param str sort: Attribute used to sort results.
        :return: list[Metric]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.metric_get_with_http_info(**kwargs)
        else:
            (data) = self.metric_get_with_http_info(**kwargs)
            return data

    def metric_get_with_http_info(self, **kwargs):
        """
        List all registered metrics
        <p>Metrics are linked to time-series and define their meaning.</p> <p>Common metric ID are listed below:</p> <table>   <tr><td>id</td><td>Value</td></tr>   <tr><td>1</td><td>Timestamp</td></tr>   <tr><td>2</td><td>Neutral</td></tr>   <tr><td>3</td><td>Happiness</td></tr>   <tr><td>4</td><td>Surprise</td></tr>   <tr><td>5</td><td>Puzzlement</td></tr>   <tr><td>6</td><td>Disgust</td></tr>   <tr><td>7</td><td>Fear</td></tr>   <tr><td>8</td><td>Sadness</td></tr> </table> <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int skip: The number of results to skip.
        :param int limit: The maximum number of results to return.
        :param str where: JSON formatted string condition.
        :param str sort: Attribute used to sort results.
        :return: list[Metric]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['skip', 'limit', 'where', 'sort']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method metric_get" % key
                )
            params[key] = val
        del params['kwargs']

        resource_path = '/metric'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'skip' in params:
            query_params['skip'] = params['skip']
        if 'limit' in params:
            query_params['limit'] = params['limit']
        if 'where' in params:
            query_params['where'] = params['where']
        if 'sort' in params:
            query_params['sort'] = params['sort']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[Metric]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def metric_metric_id_delete(self, metric_id, **kwargs):
        """
        Delete a Metric
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_metric_id_delete(metric_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int metric_id: ID of Metric to be deleted. (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.metric_metric_id_delete_with_http_info(metric_id, **kwargs)
        else:
            (data) = self.metric_metric_id_delete_with_http_info(metric_id, **kwargs)
            return data

    def metric_metric_id_delete_with_http_info(self, metric_id, **kwargs):
        """
        Delete a Metric
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_metric_id_delete_with_http_info(metric_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int metric_id: ID of Metric to be deleted. (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['metric_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method metric_metric_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'metric_id' is set
        if ('metric_id' not in params) or (params['metric_id'] is None):
            raise ValueError("Missing the required parameter `metric_id` when calling `metric_metric_id_delete`")

        resource_path = '/metric/{metric_id}'.replace('{format}', 'json')
        path_params = {}
        if 'metric_id' in params:
            path_params['metric_id'] = params['metric_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'DELETE',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Metric',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def metric_metric_id_get(self, metric_id, **kwargs):
        """
        Find a Metric
        <p>Metrics are linked to time-series and define their meaning.</p> <p>Common metric ID are listed below:</p> <table>   <tr><td>id</td><td>Value</td></tr>   <tr><td>1</td><td>Timestamp</td></tr>   <tr><td>2</td><td>Neutral</td></tr>   <tr><td>3</td><td>Happiness</td></tr>   <tr><td>4</td><td>Surprise</td></tr>   <tr><td>5</td><td>Puzzlement</td></tr>   <tr><td>6</td><td>Disgust</td></tr>   <tr><td>7</td><td>Fear</td></tr>   <tr><td>8</td><td>Sadness</td></tr> </table> <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_metric_id_get(metric_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int metric_id: ID of Metric to find. (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.metric_metric_id_get_with_http_info(metric_id, **kwargs)
        else:
            (data) = self.metric_metric_id_get_with_http_info(metric_id, **kwargs)
            return data

    def metric_metric_id_get_with_http_info(self, metric_id, **kwargs):
        """
        Find a Metric
        <p>Metrics are linked to time-series and define their meaning.</p> <p>Common metric ID are listed below:</p> <table>   <tr><td>id</td><td>Value</td></tr>   <tr><td>1</td><td>Timestamp</td></tr>   <tr><td>2</td><td>Neutral</td></tr>   <tr><td>3</td><td>Happiness</td></tr>   <tr><td>4</td><td>Surprise</td></tr>   <tr><td>5</td><td>Puzzlement</td></tr>   <tr><td>6</td><td>Disgust</td></tr>   <tr><td>7</td><td>Fear</td></tr>   <tr><td>8</td><td>Sadness</td></tr> </table> <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_metric_id_get_with_http_info(metric_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int metric_id: ID of Metric to find. (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['metric_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method metric_metric_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'metric_id' is set
        if ('metric_id' not in params) or (params['metric_id'] is None):
            raise ValueError("Missing the required parameter `metric_id` when calling `metric_metric_id_get`")

        resource_path = '/metric/{metric_id}'.replace('{format}', 'json')
        path_params = {}
        if 'metric_id' in params:
            path_params['metric_id'] = params['metric_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Metric',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def metric_post(self, body, **kwargs):
        """
        Create Metric
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_post(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param MetricCreation body: Request body (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.metric_post_with_http_info(body, **kwargs)
        else:
            (data) = self.metric_post_with_http_info(body, **kwargs)
            return data

    def metric_post_with_http_info(self, body, **kwargs):
        """
        Create Metric
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.metric_post_with_http_info(body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param MetricCreation body: Request body (required)
        :return: Metric
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method metric_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `metric_post`")

        resource_path = '/metric'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Metric',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))
