# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class TimeseriesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def timeseries_delete(self, response_id, **kwargs):
        """
        Delete a Timeseries
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.timeseries_delete(response_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int response_id: ID of the Response associated to the TimeSeries. (required)
        :param int metric_id: ID of the Metric of the Timeseries to be deleted.
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.timeseries_delete_with_http_info(response_id, **kwargs)
        else:
            (data) = self.timeseries_delete_with_http_info(response_id, **kwargs)
            return data

    def timeseries_delete_with_http_info(self, response_id, **kwargs):
        """
        Delete a Timeseries
        <p><strong>Permissions:</strong> ✗ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.timeseries_delete_with_http_info(response_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int response_id: ID of the Response associated to the TimeSeries. (required)
        :param int metric_id: ID of the Metric of the Timeseries to be deleted.
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['response_id', 'metric_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method timeseries_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'response_id' is set
        if ('response_id' not in params) or (params['response_id'] is None):
            raise ValueError("Missing the required parameter `response_id` when calling `timeseries_delete`")

        resource_path = '/timeseries'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'response_id' in params:
            query_params['response_id'] = params['response_id']
        if 'metric_id' in params:
            query_params['metric_id'] = params['metric_id']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'DELETE',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='str',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))

    def timeseries_get(self, response_id, **kwargs):
        """
        Get all recorded timeseries for a Response
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.timeseries_get(response_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int response_id: ID of the Response associated to the TimeSeries. (required)
        :param int metric_id: ID of the Metric associated to the TimeSeries.
        :param bool normalize: Return data beetwen 0 and 1. Default: false.
        :param str format: If value is 'csv' then data is passed back in CSV format insted of the default time-series format. Example: csv.
        :return: list[Timeseries]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.timeseries_get_with_http_info(response_id, **kwargs)
        else:
            (data) = self.timeseries_get_with_http_info(response_id, **kwargs)
            return data

    def timeseries_get_with_http_info(self, response_id, **kwargs):
        """
        Get all recorded timeseries for a Response
        <p><strong>Permissions:</strong> ✓ Respondent ✗ Customer ✓ Manager</p>

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.timeseries_get_with_http_info(response_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int response_id: ID of the Response associated to the TimeSeries. (required)
        :param int metric_id: ID of the Metric associated to the TimeSeries.
        :param bool normalize: Return data beetwen 0 and 1. Default: false.
        :param str format: If value is 'csv' then data is passed back in CSV format insted of the default time-series format. Example: csv.
        :return: list[Timeseries]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['response_id', 'metric_id', 'normalize', 'format']
        all_params.append('callback')
        all_params.append('_return_http_data_only')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method timeseries_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'response_id' is set
        if ('response_id' not in params) or (params['response_id'] is None):
            raise ValueError("Missing the required parameter `response_id` when calling `timeseries_get`")

        resource_path = '/timeseries'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'response_id' in params:
            query_params['response_id'] = params['response_id']
        if 'metric_id' in params:
            query_params['metric_id'] = params['metric_id']
        if 'normalize' in params:
            query_params['normalize'] = params['normalize']
        if 'format' in params:
            query_params['format'] = params['format']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['api_key']

        return self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[Timeseries]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'))
