# coding: utf-8

"""
    CloudEmotion API v1

    CrowdEmotion API

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.content_details import ContentDetails
from .models.data import Data
from .models.face_video import FaceVideo
from .models.face_video_upload import FaceVideoUpload
from .models.login import Login
from .models.login_response import LoginResponse
from .models.media import Media
from .models.media_creation import MediaCreation
from .models.metric import Metric
from .models.metric_creation import MetricCreation
from .models.research import Research
from .models.research_creation import ResearchCreation
from .models.respondent import Respondent
from .models.respondent_metadata import RespondentMetadata
from .models.respondent_metadata_response import RespondentMetadataResponse
from .models.response import Response
from .models.response_creation import ResponseCreation
from .models.response_metadata import ResponseMetadata
from .models.response_metadata_response import ResponseMetadataResponse
from .models.statistics import Statistics
from .models.stats import Stats
from .models.status import Status
from .models.tags import Tags
from .models.timeseries import Timeseries
from .models.user import User
from .models.user_metadata import UserMetadata
from .models.user_metadata_response import UserMetadataResponse
from .models.user_update_body import UserUpdateBody
from .models.videodetails import Videodetails

# import apis into sdk package
from .apis.face_video_api import FaceVideoApi
from .apis.media_api import MediaApi
from .apis.metric_api import MetricApi
from .apis.research_api import ResearchApi
from .apis.respondent_api import RespondentApi
from .apis.response_api import ResponseApi
from .apis.timeseries_api import TimeseriesApi
from .apis.user_api import UserApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
